### ISSUE TITLE
Implement heapster_init_env_from_file

### ISSUE THREAD

**Issue by eddywestbrook** [GaloisInc/heapster-saw#1]
Implement a command `heapster_init_env_from_file` that is like `heapster_init_env` but loads an initial SAW core module from a file.

This code for this will be next to `heapster_init_env`, [here](https://github.com/GaloisInc/saw-script/blob/wip-heapster/src/SAWScript/HeapsterBuiltins.hs#L178), and a lot can probably borrowed from that function. The command can be added to the SAW interpreter in manner similar to [here](https://github.com/GaloisInc/saw-script/blob/wip-heapster/src/SAWScript/Interpreter.hs#L2244).

It will need to parse and type-check SAW core modules. The [`readModuleFromFile`](https://github.com/GaloisInc/saw-core/blob/master/src/Verifier/SAW/ParserUtils.hs#L56) function shows how to parse a SAW core module from a file. It would be better to rewrite `readModuleFromFile` and replace calls to `error` with calls to `fail` so SAW does not quit if there is a parse error. To type-check a parsed, untyped module, call [`tcInsertModule`](https://github.com/GaloisInc/saw-core/blob/master/src/Verifier/SAW/Typechecker.hs#L418). Note that the pattern-match at the beginning of that function also shows how to extract the `ModuleName` from an untyped module.

**Comment by eddywestbrook** [comment]
Oh, right, and the test file is [here](https://github.com/GaloisInc/heapster-saw/blob/master/examples/string_set.saw)

**Comment by m-yac** [comment]
Done - see the relevant commits in [saw-script](https://github.com/GaloisInc/saw-script/commit/8fa74c44b6108d0f26996a18da71f179ee428a5b), [saw-core](https://github.com/GaloisInc/saw-core/commit/db42e86023fc1c0bbe17c402f81e5cb498004dc3), and [heapster-saw](https://github.com/GaloisInc/heapster-saw/commit/a1dbf34e68506841db6dc6572a0cf3cc7b428aa3). Notice that I moved the definitions relevant to the `string_set` example out of the prelude and into a `string_set.sawcore` file. Let me know if any part of this doesn't work for you @eddywestbrook.

And btw thanks for giving me such a clear roadmap, it made this super easy! Sorry for taking so long to get started.

**Comment by eddywestbrook** [comment]
Sweet! Good job, @m-yac!
