### ISSUE TITLE
Support GHC 8.6 and newer

### ISSUE THREAD

**Issue by karljs** [GaloisInc/heapster-saw#10]
Currently, when building the saw-script repo with this is as submodule, builds using anything but GHC 8.4 fail.  This will track the necessary changes for GHC 8.6 support, and depending on the amount of changes, also GHC 8.8

**Comment by eddywestbrook** [comment]
Hey @karljs, is this finished?

**Comment by karljs** [comment]
Whoops, it sure is.  Closing.
