### ISSUE TITLE
Change the translation of the unit type to not have computational content

### ISSUE THREAD

**Issue by eddywestbrook** [GaloisInc/heapster-saw#17]
There should be a new `ExprTrans` constructor `ETrans_Unit :: ExprTrans UnitType`. Every use of `ETrans_Term unitOpenTerm` should be replaced by `ETrans_Unit`.

**Comment by m-yac** [comment]
I made this change but it doesn't affect the generated coq at all. Is that expected?

If the goal is to get rid of the unnecessary `Unit`s in the generated coq, it looks like we will have to modify `sigmaTransM` to check whether its second argument is empty.

**Comment by eddywestbrook** [comment]
It should only matter for functions whose LLVM return type is unit. In this case, the translation of the function should have return type `[| p_out |]` instead of `Sigma #() (\ (_:#()) -> [| p_out |]` (written in SAW core notation), where `p_out` is the output permissions of the function. Two examples are the `string_set_insert` and `string_set_remove` functions in `string_set.c`.

**Comment by m-yac** [comment]
Ah, I was just missing the `UnitRepr` case. This is done in 2133264018f950e9221e8f9a305e9b3830659688.

**Comment by eddywestbrook** [comment]
Awesome, this looks great!
