### ISSUE TITLE
Allow terms in heapster_assume_fun

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/heapster-saw#2]
Allow `heapster_assume_fun` to accept arbitrary terms in its final argument, rather than just identifiers. See [this test file](https://github.com/GaloisInc/heapster-saw/blob/master/examples/string_set.saw).

I'm going to start working on this now.

**Comment by eddywestbrook** [comment]
@m-yac: you will need to add a new definition to the current module as part of this, as the `PermEnv` structure does require an identifier and not just an arbitrary SAW core term (for reasons). You can do this using `scModifyModule`, and example of which is [here](https://github.com/GaloisInc/heapster-saw/blob/master/src/Verifier/SAW/Heapster/SAWTranslation.hs#L3320). To get the necessary type, use `translateCompleteFunPerm` in `SAWTranslation.hs`.

**Comment by eddywestbrook** [comment]
Also: you can use the string name of the C function passed to `heapster_assume_fun` as the name of the new identifier. You could also, if you feel like it, make a special case where if the term passed to `heapster_assume_fun` turns out to be an identifier, then just use it rather than adding it as a definition. Though it would be good to check that the identifier has the correct type, as given by `translateCompleteFunPerm`.

**Comment by m-yac** [comment]
Great, most of this I already did! I'm pushing my code now so you can see too.

What I didn't do is actually get the expected type from `translateCompleteFunPerm` and check that the term has this type. What's the best way to do this? Currently I get it's type from `typeInferComplete` [here](https://github.com/GaloisInc/saw-script/blob/wip-heapster/src/SAWScript/HeapsterBuiltins.hs#L210).

**Comment by m-yac** [comment]
I also have two questions that I left as comments on [this line](https://github.com/GaloisInc/saw-script/blob/wip-heapster/src/SAWScript/HeapsterBuiltins.hs#L203).

> You could also, if you feel like it, make a special case where if the term passed to heapster_assume_fun turns out to be an identifier, then just use it rather than adding it as a definition.

I'll definitely add that.

**Comment by eddywestbrook** [comment]
One easy way is to put the expected type into the `defType` field when you call `insDef`. But you could also call [`scConvertible`](https://github.com/GaloisInc/saw-core/blob/master/src/Verifier/SAW/SharedTerm.hs#L728) if you would rather check the error before calling `insDef`, e.g., to get a more specific error message.

**Comment by m-yac** [comment]
Ah, `scConvertible` is what I was looking for - thanks!

**Comment by eddywestbrook** [comment]
It looks like `Data.ByteString.Lazy.UTF8` exposes a `fromString` method. You can use "<interactive>" or something like that for both the `base` and `path` arguments for `parseSAWTerm`. See [here](https://github.com/GaloisInc/saw-script/blob/master/src/SAWScript/Builtins.hs#L1224), which does this exact thing.

**Comment by m-yac** [comment]
Looks like `translateCompleteFunPerm` doesn't wrap the return type in `CompM`, so `scConvertible` fails for every example. I'll take a look at this tomorrow.

**Comment by eddywestbrook** [comment]
Crap, I'm looking at that now...

**Comment by eddywestbrook** [comment]
Ok, that's fixed. Should be good now. Looks like nothing was actually using the result of that translation anywhere...

**Comment by m-yac** [comment]
Great, thanks! The [latest commit](https://github.com/GaloisInc/saw-script/commit/114ae86c10ffe9b0aba294e30afa7f5c762e2069) on `wip-heapster` should have this working now.

**Comment by eddywestbrook** [comment]
Looks good!
