### ISSUE TITLE
Fix stylistic concerns in HeapsterBuiltins.hs

### ISSUE THREAD

**Issue by eddywestbrook** [GaloisInc/heapster-saw#24]
A number of functions have crept into the code in `HeapsterBuiltins.hs` that really belong behind the abstraction boundaries in their respective modules. Specifically, `runTransM` and its accompanying `completeOpenTerm` belong inside the `SAWTranslation` module, while `runParser` and `mkParserEnv` belong inside the `PermParser` module. Instead, top-level entrypoints to these modules should be added at the bottom of the code to perform the high-level actions that are needed, such as translating a permission in an expression context or parsing a context. (The `SAWTranslation` module has a section at the bottom labeled for top-level entrypoints, and I am about to add the same to the `PermParser` module.)

This also includes the two uses of `runTCM`, which should become new functions in the `SCTypeCheck` module in `saw-core` just like `scTypeCheck`.

Additionally, there are a number of code patterns that are repeated which should be abstracted into their own functions. For example, there is a lot of code that pattern-matches on an `Either` type and `fail`s in the `Left` case that could be replaced by a single function call.

**Comment by eddywestbrook** [comment]
Note: I am adding `failOnLeft` to `HeapsterBuiltins`

**Comment by eddywestbrook** [comment]
Note: we also need to get better at adding a Haddock comment to the front of every function

**Comment by m-yac** [comment]
Ok, in the latest three commits on `saw-script` (https://github.com/GaloisInc/saw-script/commit/7b8b38200e62cc6012766ec15e276dece89a3e18 - https://github.com/GaloisInc/saw-script/commit/68a029a2cf87f0d212e364a30c386e30ef6d319e) I've moved appropriate functions from `HeapsterBuiltins` to `SAWTranslation`, `PermParser`, and `SCTypeCheck`.

In terms of style though, there are still a two other small things I think could be easily improved in `HeapsterBuiltins`, but I wanted to check with you first, @eddywestbrook. 
- A common pattern in this file is:
   ```
     some_args <- parseCtxString "argument types" env args_str
     some_tp <- parseTypeString "permission type" env tp_str
     case (some_args, some_tp) of
       (Some args, Some tp_perm) -> do
         ...
   ```
   Is there any reason not to change it to the following? This would cut down on a lot of indentation.

   ```
     Some args <- parseCtxString "argument types" env args_str
     Some tp_perm <- parseTypeString "permission type" env tp_str
     ...
   ```
- This file generates there are a ton of "Defined but not used" warnings. I would love to get rid of those. (This also goes for other files!)

**Comment by eddywestbrook** [comment]
@m-yac: I guess I didn't know GHC could handle that sort of pattern in `do`-notation. It didn't used to be able to. Maybe that shows my age? :)

But yes, go for it!

**Comment by m-yac** [comment]
Awesome! Done in https://github.com/GaloisInc/saw-script/commit/64bebe8685a58063404dcad26af75e5c5cffc571.

**Comment by m-yac** [comment]
Just pushed a bit more cleanup (https://github.com/GaloisInc/saw-script/commit/7a2c74ef685e1cc71f219c9fceb6a3bc7e9c0cfe) in the same vein, also adding a `failOnNothing` function in the style of `failOnLeft`, which I used in `heapster_block_entry_hint`, `heapster_assume_fun`, and `heapster_typecheck_mut_funs`.
