### ISSUE TITLE
Permissions abbreviation bug

### ISSUE THREAD

**Issue by karljs** [GaloisInc/heapster-saw#39]
Currently, we can't use some permissions abbreviations without an error and I haven't dived into why that is.  Here's an examle that does not work:

```
heapster_define_perm env "int64" " " "llvmptr 64" "exists x:bv 64.eq(llvmword(x))";
heapster_define_perm env "state_t" " " "llvmptr 64" "array(0, <16, *1, [(W,0) |-> int64<>]))";
```

I tried to apply the following permissions to the `sub_bytes` function in Charybdis:
```
heapster_typecheck_fun env "sub_bytes" "().arg0:state_t<> -o arg0:state_t<>";
```
And I get the following error
```
Function application with non-function type
  let { x@1 = Prelude.bitvector 64
    }
 in Prelude.CompM
      (Prelude.BVVec 64
         [Prelude.False
         ,Prelude.False
         ... <snip a bunch more zeros> ...
         ,Prelude.False
         ,Prelude.False
         ,Prelude.False
         ,Prelude.True
         ,Prelude.False
         ,Prelude.False
         ,Prelude.False
         ,Prelude.False]
         (Prelude.Sigma x@1 (\(x_ex0 : x@1) -> #(-empty-))))
```

If I inline the definition of `state_t` as follows, I get no errors:

```
heapster_typecheck_fun env "sub_bytes" "().arg0:array(0, <16, *1, [(W,0) |-> int64<>]) -o arg0:array(0, <16, *1, [(W,0) |-> int64<>])";
```

One thing I haven't tested yet is whether this happens only when we nest permissions abbreviations, but I imagine that's worth investigating.

**Comment by eddywestbrook** [comment]
This seems to have been fixed by [73c8d8b](https://github.com/GaloisInc/heapster-saw/commit/73c8d8b39ecddc559c661ed23b2bcb1c4ddeee7d)
