### ISSUE TITLE
Change the definition of `BVVec` to use normal `Vec`

### ISSUE THREAD

**Issue by eddywestbrook** [GaloisInc/heapster-saw#59]
We should be able to define `BVVec n w a = Vec (bvToNat n w) a`. The associated `BVVec` operators will need to be updated to work with this, and we need to check that there are no definitional equalities that break, though I don't imagine there will be because this definition makes strictly more things definitionally equal...

**Comment by m-yac** [comment]
Resolved by Galoisinc/saw-core@73c5ef7
